config/routes.rb
Rails.application.routes.draw do
  resources :sits
  resources :sitters
  resources :pets
  resources :people
  get 'asdf/new'
  resources :users
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
  get '/foo', to: 'foo#index'
  post '/foo', to: 'foo#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  # if :parent is false, parent is is sorta really the post
  belongs_to :parent, class_name: "Comment", optional: true
  has_many :children, class_name: "Comment", foreign_key: "parent_id"
end

app/models/person.rb
class Person < ApplicationRecord
  has_and_belongs_to_many :pets
  has_many :sits
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_and_belongs_to_many :people
  enum species: [:unknown, :cat, :dog], _suffix: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/models/sit.rb
class Sit < ApplicationRecord
  belongs_to :person
  belongs_to :sitter
end

app/models/sitter.rb
class Sitter < ApplicationRecord
  has_many :sits
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, allow_nil: true
  has_secure_password
    
end

app/controllers/asdf_controller.rb
class AsdfController < ApplicationController
  def new
  end
end

app/controllers/foo_controller.rb
class FooController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index

  end
  def new
  end
  def create
    flash[:success] = "Ia Ia! Chthulu ftagn!"
    render 'index'
  end
  
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.fetch(:pet, {})
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user, :title, :content)
    end
end

app/controllers/sits_controller.rb
class SitsController < ApplicationController
  before_action :set_sit, only: %i[ show edit update destroy ]

  # GET /sits or /sits.json
  def index
    @sits = Sit.all
  end

  # GET /sits/1 or /sits/1.json
  def show
  end

  # GET /sits/new
  def new
    @sit = Sit.new
  end

  # GET /sits/1/edit
  def edit
  end

  # POST /sits or /sits.json
  def create
    
    @sit = Sit.new(sit_params)

    respond_to do |format|
      if @sit.save
        format.html { redirect_to @sit, notice: "Sit was successfully created." }
        format.json { render :show, status: :created, location: @sit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sits/1 or /sits/1.json
  def update
    respond_to do |format|
      if @sit.update(sit_params)
        format.html { redirect_to @sit, notice: "Sit was successfully updated." }
        format.json { render :show, status: :ok, location: @sit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sits/1 or /sits/1.json
  def destroy
    @sit.destroy
    respond_to do |format|
      format.html { redirect_to sits_url, notice: "Sit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sit
      @sit = Sit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sit_params
      d = params[:sit]
      $stderr.puts d.inspect.green
      date = DateTime.new(d["date(1i)"].to_i,
                            d["date(2i)"].to_i,
                            d["date(3i)"].to_i,
                            d["date(4i)"].to_i,
                            d["date(5i)"].to_i)
      til = DateTime.new(d["date(1i)"].to_i,
                            d["untiltime(2i)"].to_i,
                            d["untiltime(3i)"].to_i,
                            d["untiltime(4i)"].to_i,
                            d["untiltime(5i)"].to_i)
      dur = ((til - date) * 24*60).to_i
      $stderr.puts date.inspect.green
      $stderr.puts til.inspect.green
      params[:sit][:date] = date
      params[:sit][:untiltime] = til
      params[:sit][:duration] = dur
      $stderr.puts params.inspect.green
      params.require(:sit).permit(:person_id, :sitter_id, :date, :untiltime, :duration)
      
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asdf_helper.rb
module AsdfHelper
end

app/helpers/foo_helper.rb
module FooHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def logged_in?
  end
  def current_user(user)
    if (user_id == session[:user_id])
      @current_user = User.find_by(id: user_id)
    end
  end

end

app/helpers/sits_helper.rb
module SitsHelper
end

app/helpers/sitters_helper.rb
module SittersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.species %></td>
        <td><%= pet.owner %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'layouts/header' %>
<H1>Welcome to this place!</H1>
<%= link_to 'Foo', foo_path %>
<%= link_to 'Pet sitting', sits_path %>
<%= link_to 'Pet owners', people_path %>
<%= link_to 'Pets', pets_path %>
<%= link_to 'Pet sitters', sitters_path %>

<div class="body_column">

  <%= @posts.each do |post| %>
    <div class="post_container">
      <h4><%= post.title %></h4>
      
      <p><%= post.content %></p>
      <h
      5><%= post.user %></h6>
      <% post.comments.each do |comment| %>
        <% if comment.parent == nil %>
          <div class="comment" >
        
            <p><%= comment.content %></p>
            <p><%= comment.user %></p>
            <% comment.children.each do  |child | %>
              <div class="comment">
                <p><%= child.content %></p>
                <p><%= child.user %></p>
              </div>
            <% end %>

          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/sits/_form.html.erb
<%= form_with(model: sit) do |form| %>
  <% if sit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sit.errors.count, "error") %> prohibited this sit from being saved:</h2>

      <ul>
        <% sit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.collection_select :person_id, Person.all, :id, :name %>
  <%= form.collection_select :sitter_id, Sitter.all, :id, :name %>

  <%= form.label :date %>
  <%= form.datetime_select :date %>
  <%# form.label :duration %>
  <%# form.time_select :duration %>
  <%= form.label :untiltime %>
  <%= form.datetime_select :untiltime %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sits/edit.html.erb
<h1>Editing Sit</h1>

<%= render 'form', sit: @sit %>

<%= link_to 'Show', @sit %> |
<%= link_to 'Back', sits_path %>

app/views/sits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sits</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sits.each do |sit| %>
      <tr>
        <td>Owner: <%=sit.person.name%></td>
        <td>Sitter: <%=sit.sitter.name%></td>
        <td>Time: <%=sit.date%></td>
        <td>Duration<%=sit.duration%></td>
        <td><%= link_to 'Show', sit %></td>
        <td><%= link_to 'Edit', edit_sit_path(sit) %></td>
        <td><%= link_to 'Destroy', sit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sit', new_sit_path %>

app/views/sits/new.html.erb
<h1>New Sit</h1>

<%= render 'form', sit: @sit %>

<%= link_to 'Back', sits_path %>

app/views/sits/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sit_path(@sit) %> |
<%= link_to 'Back', sits_path %>