config/routes.rb
Rails.application.routes.draw do
  resources :sits
  resources :sitters
  resources :pets
  resources :people
  get 'asdf/new'
  resources :users
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
  get '/foo', to: 'foo#index'
  post '/foo', to: 'foo#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
end

app/models/sitter.rb
class Sitter < ApplicationRecord
  has_many :sits
end

app/controllers/sitters_controller.rb
class SittersController < ApplicationController
  before_action :set_sitter, only: %i[ show edit update destroy ]

  # GET /sitters or /sitters.json
  def index
    @sitters = Sitter.all
  end

  # GET /sitters/1 or /sitters/1.json
  def show
  end

  # GET /sitters/new
  def new
    @sitter = Sitter.new
  end

  # GET /sitters/1/edit
  def edit
  end

  # POST /sitters or /sitters.json
  def create
    @sitter = Sitter.new(sitter_params)

    respond_to do |format|
      if @sitter.save
        format.html { redirect_to @sitter, notice: "Sitter was successfully created." }
        format.json { render :show, status: :created, location: @sitter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sitters/1 or /sitters/1.json
  def update
    respond_to do |format|
      if @sitter.update(sitter_params)
        format.html { redirect_to @sitter, notice: "Sitter was successfully updated." }
        format.json { render :show, status: :ok, location: @sitter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sitters/1 or /sitters/1.json
  def destroy
    @sitter.destroy
    respond_to do |format|
      format.html { redirect_to sitters_url, notice: "Sitter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sitter
      @sitter = Sitter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sitter_params
      params.fetch(:sitter, {})
    end
end

app/helpers/sitters_helper.rb
module SittersHelper
end

app/views/sitters/_form.html.erb
<%= form_with(model: sitter) do |form| %>
  <% if sitter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sitter.errors.count, "error") %> prohibited this sitter from being saved:</h2>

      <ul>
        <% sitter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :email %>
  <%= form.text_field :email %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sitters/edit.html.erb
<h1>Editing Sitter</h1>

<%= render 'form', sitter: @sitter %>

<%= link_to 'Show', @sitter %> |
<%= link_to 'Back', sitters_path %>

app/views/sitters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sitters</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sitters.each do |sitter| %>
      <tr>
        <td><%= sitter.name %></td>
        <td><%= link_to 'Show', sitter %></td>
        <td><%= link_to 'Edit', edit_sitter_path(sitter) %></td>
        <td><%= link_to 'Destroy', sitter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sitter', new_sitter_path %>

app/views/sitters/new.html.erb
<h1>New Sitter</h1>

<%= render 'form', sitter: @sitter %>

<%= link_to 'Back', sitters_path %>

app/views/sitters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sitter_path(@sitter) %> |
<%= link_to 'Back', sitters_path %>