config/routes.rb
Rails.application.routes.draw do
  resources :sits
  resources :sitters
  resources :pets
  resources :people
  get 'asdf/new'
  resources :users
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
  get '/foo', to: 'foo#index'
  post '/foo', to: 'foo#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  # if :parent is false, parent is is sorta really the post
  belongs_to :parent, class_name: "Comment", optional: true
  has_many :children, class_name: "Comment", foreign_key: "parent_id"
end

app/models/person.rb
class Person < ApplicationRecord
  has_and_belongs_to_many :pets
  has_many :sits
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_and_belongs_to_many :people
  enum species: [:unknown, :cat, :dog], _suffix: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/models/sit.rb
class Sit < ApplicationRecord
  belongs_to :person
  belongs_to :sitter
end

app/models/sitter.rb
class Sitter < ApplicationRecord
  has_many :sits
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, allow_nil: true
  has_secure_password
    
end

app/controllers/asdf_controller.rb
class AsdfController < ApplicationController
  def new
  end
end

app/controllers/foo_controller.rb
class FooController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index

  end
  def new
  end
  def create
    flash[:success] = "Ia Ia! Chthulu ftagn!"
    render 'index'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asdf_helper.rb
module AsdfHelper
end

app/helpers/foo_helper.rb
module FooHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def logged_in?
  end
  def current_user(user)
    if (user_id == session[:user_id])
      @current_user = User.find_by(id: user_id)
    end
  end

end

app/helpers/sits_helper.rb
module SitsHelper
end

app/helpers/sitters_helper.rb
module SittersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class="nav nav_left">
    <div class="nav_item asdf" >ASDF</div>
  </div>
  <div class="nav nav_right">
    <%= link_to "Sign up", signup_path %>
    <%= link_to "Log in", login_path %>
    <div class="nav_item">Something else</div>
  </div>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asdf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |msg_type, msg| %>
      <h2><%= msg_type%>: <%= msg %></h2> 
    <% end %>
    <%= yield %>
    <%= params.inspect %>
    <%= session.inspect %>
    <%= session.class %>

  </body>
</html>

app/views/shared/_errors.html.erb
  <% if object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(object.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% object.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>